### ISSUE TITLE
When press Crtl + Alt + L ==> Console log will appear in the last line of script in .vue file

### ISSUE THREAD

**Issue by harrytran998** [Chakroun-Anas/turbo-console-log#108]
It's an example. After I update the Extention and reload, this stuff happen. And only in Vue file, I checked another file like `.ts` or `.js` it's totally ok!
Vue file have the structure like this.
```vue
<template></template>
<script>
export default defineComponent({
 setup() {
  function foo() {}
  return { foo }
 }
})
</script>

```

![image](https://user-images.githubusercontent.com/24296018/99928291-0602b480-2d7b-11eb-80ad-f25cff12eec5.png)

**Comment by praburangki** [comment]
This is also happening on a `.ts` file. I've downgraded to v2.1.0 and it's back to normal.

**Comment by chakroun-anas-contentsquare** [comment]
Hello, a fix is coming soon 🙂

**Comment by harrytran998** [comment]
> Hello, a fix is coming soon 🙂

Thank you for your work ❤️.

**Comment by PeterLAxakon** [comment]
> This is also happening on a `.ts` file. I've downgraded to v2.1.0 and it's back to normal.

can confirm this, not working as expected in .ts files

**Comment by Chakroun-Anas** [comment]
Hello guys,

I need you please to share with me the snippet of code where the extension is not inserting the log message in the right line, this will help me check if the fix is covering all cases (each different case will have its test scenario).

Thx in advance.

**Comment by Chakroun-Anas** [comment]
I just pushed a version that should deal with this (2.1.4), but as i said above, i need you please to verify and share with me the snippet of code where the extension was not working properly so that we create test cases for each different scenario and make it more robust 😉, thx.

**Comment by itsalb3rt** [comment]
And simple js file. I press Crtl + Alt + L in line 82 `error` and the out put in 97 and 98 line. In another function.



![image](https://user-images.githubusercontent.com/35310226/100483364-15f9fb80-30cf-11eb-83da-9cf43290a13a.png)

**Comment by LawsonNguyen** [comment]
The same issue

**Comment by LawsonNguyen** [comment]
> This is also happening on a `.ts` file. I've downgraded to v2.1.0 and it's back to normal.

Got into the situation with v2.1.0 . It works well with v2.0.4

**Comment by PeterLAxakon** [comment]
@Chakroun-Anas I'm glad you are working on this, unfortunately this is still an issue in typescript. 
![1 error](https://user-images.githubusercontent.com/61692826/100977488-58915d00-3541-11eb-9749-2bd4401e35d4.png)
in this function I want to console log the parameter, I'm using the Crtl + Alt + L 
In the first example the console log is inserted under the function itself. 

However if I start the function with a new/blank line it seems to insert the console log at the right place:
![2 works](https://user-images.githubusercontent.com/61692826/100977665-91313680-3541-11eb-85a5-361450713547.png)

**Comment by Chakroun-Anas** [comment]
@PeterLAxakon I just pushed a version (v2.1.6) that deals with this, please test again and give me your feedback, thank you for making the extension better.

@itsalb3rt Unfortunately i need the whole context of the variable so that i can help you, anyway, hopefully that the last version (v2.1.6)  that i just pushed deals with your use case, if not please share with me the whole context of the variable so that i can fix that, thank you.

**Comment by DexterLawson** [comment]
> @PeterLAxakon I just pushed a version (v2.1.6) that deals with this, please test again and give me your feedback, thank you for making the extension better.
> 
> @itsalb3rt Unfortunately i need the whole context of the variable so that i can help you, anyway, hopefully that the last version (v2.1.6) that i just pushed deals with your use case, if not please share with me the whole context of the variable so that i can fix that, thank you.

Confirm : It works
<img width="641" alt="Screen Shot 2020-12-07 at 12 14 15" src="https://user-images.githubusercontent.com/72881474/101312211-c44b3100-3885-11eb-805e-f73ece58fa67.png">

**Comment by itsalb3rt** [comment]
> @PeterLAxakon I just pushed a version (v2.1.6) that deals with this, please test again and give me your feedback, thank you for making the extension better.
> 
> @itsalb3rt Unfortunately i need the whole context of the variable so that i can help you, anyway, hopefully that the last version (v2.1.6) that i just pushed deals with your use case, if not please share with me the whole context of the variable so that i can fix that, thank you.

In my case it has not been solved but I have discovered that if the functions have similar names (like the code that I will put below) the output of Crtl + Alt + L jumps to the other function.

```javascript
/**
 * Get extensions by account number
 */
function* fetchExtensions(action) {
    try {
    } catch (error) {
        // dispatch a failure action to the store with the error
        yield put(actions.error(types.FETCH_EXTENSIONS.ERROR, error, true));
        yield cps({ context, fn }, { redirect: false });
    }
}

/**
 * Get extension by id
 */
function* fetchExtension(action) {
    try {
    } catch (error) {
        if (error.hasOwnProperty('code') && error.code === 400) {
            yield put(actions.error(types.FETCH_EXTENSION.ERROR, error, true));
        } else {
            yield put(actions.error(types.FETCH_EXTENSION.ERROR));
        }
    }
}
```

![image](https://user-images.githubusercontent.com/35310226/101356612-b4742280-386e-11eb-8db4-d3d5ee9c7628.png)

**Comment by PeterLAxakon** [comment]
> @PeterLAxakon I just pushed a version (v2.1.6) that deals with this, please test again and give me your feedback, thank you for making the extension better.
> 
> @itsalb3rt Unfortunately i need the whole context of the variable so that i can help you, anyway, hopefully that the last version (v2.1.6) that i just pushed deals with your use case, if not please share with me the whole context of the variable so that i can fix that, thank you.

thank you, it now works with parameters.
